/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/xoQivtMqJtc
 */
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";

function GameBugsTooltip() {
  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <button className="inline-flex items-center rounded-md border border-gray-200 border-transparent bg-gray-900 px-2.5 py-0.5 text-xs font-semibold text-gray-50 shadow transition-colors hover:bg-gray-900/80 focus:outline-none dark:border-gray-800 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/80">
            Hover Me
          </button>
        </TooltipTrigger>
        <TooltipContent className="max-w-[16rem] transition-all duration-200 ease-in-out">
          <p className="text-md">
            The game is still a work in progress! Please be patient with bugs,
            best thing to do is just refresh the page, or create a new game!
            Also, we unfortunately still need more time with the Mina
            integration, but the contract and worker client can be found{" "}
            <a
              href="https://github.com/vixuslabs/zkArcade/tree/main/packages/mina"
              rel="noreferrer"
              className="inline-block underline underline-offset-1 hover:text-primary"
            >
              here
            </a>
          </p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
}

export default GameBugsTooltip;
