/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    carrier: THREE.Mesh;
    tower: THREE.Mesh;
  };
  materials: {
    carrier: THREE.MeshStandardMaterial;
  };
};

export function Carrier(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/assets/zkBattleships/carrier.glb",
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} scale={0.1}>
      <mesh
        geometry={nodes.carrier.geometry}
        material={materials.carrier}
        scale={[2, 0.5, 0.5]}
      >
        <mesh
          geometry={nodes.tower.geometry}
          material={materials.carrier}
          scale={[0.121, 0.515, 0.357]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/assets/zkBattleships/carrier.glb");
